# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - main
    - dev
  pull_request:

    


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      working-directory: ./ui
      run: sudo npm install

    - name: Start containers
      run: docker-compose -f "ui/docker-compose.yml" up -d --build
    
    - name: Sleep for 5 minutes
      uses: jakejarvis/wait-action@master
      with:
        time: '5m'
    
    - name: Check running containers
      run: docker ps

    - name: Run tests
      working-directory: ./ui
      run: npm run test

    - name: Stop containers
      if: always()
      run: docker-compose -f "ui/docker-compose.yml" down
